
# [Multiple,Single] Object Tracking
#   one of: ['none', 'mot_stf','sot_stf']
output_format='none'

# The following dumpers give the ability to dump out video frames, mainly used for debugging purposes
#   ['none', dump_original', 'dump_grey', 'dump_optical_flow', 'dump_annotated', 'dump_masked_background', 'all']
frame_dumpers='none'

input_dir='input'
output_dir='output'

# Options
#  video = video playback
#  camera = camera stream
controller='video'

enable_cuda=false

[Visualizer]

# Options
#  noop = No visualisation at all, just a console entry
#  simple = Displays single image with annotations, annotations are also in console output
#  two_by_two = Displays 2x2 images incl image with annotations, background subtraction and keypoints, annotations
#    are also in console output
format='noop'
max_display_dim=1080


[VideoTracker]

mask_pct=20
# Detects small, medium and large objects
sensitivity=1
resize_frame=true
noise_reduction=true

# The max number of concurrent active trackers
max_active_trackers=10

# Detection Mode
#   one of: 'background_subtraction'
detection_mode='background_subtraction'

calculate_optical_flow=true

[Camera]

camera_mode='rtsp'
# N.B. place camera_uri in secrets.toml
