
# [Multiple,Single] Object Tracking
#   one of: ['none', 'mot_stf','sot_stf']
output_format='mot_stf'

# The following dumpers give the ability to dump out video frames, mainly used for debugging purposes
#   ['none', dump_original', 'dump_grey', 'dump_optical_flow', 'dump_annotated', 'dump_masked_background', 'all']
frame_dumpers='none'

input_dir='input'
output_dir='output'

# Options
#  video = video playback
#  camera = camera stream
controller='video'

[Visualizer]

# Options
#  noop = No visualisation at all, just a console entry
#  simple = Displays single image with annotations, annotations are also in console output
#  two_by_two = Displays 2x2 images incl image with annotations, background subtraction and keypoints, annotations
#    are also in console output
format='two_by_two'
max_display_dim=1080
font_size=0.75
font_thickness=2

[VideoTracker]

# Tracker Type
#   currently only CSRT is supported
tracker_type='CSRT'

# Background Subtractor Type
#   one of: 'KNN', 'MOG', 'MOG2', 'BGS_FD', 'BGS_SFD', 'BGS_WMM', 'BGS_WMV', 'BGS_ABL', 'BGS_ASBL', 'BGS_MOG2',
#           'BGS_PBAS', 'BGS_SD', 'BGS_SuBSENSE', 'BGS_LOBSTER', 'BGS_PAWCS', 'BGS_TP', 'BGS_VB', 'BGS_CB'
#   If CUDA is enabled then one if: 'MOG_CUDA', 'MOG2_CUDA'
background_subtractor_type='KNN'
background_subtractor_learning_rate=0.05

enable_cuda=false
enable_stopwatch=false

# Detects small, medium and large objects
sensitivity=1
resize_frame=false
resize_dimension=1440
noise_reduction=false
blur_radius=3

# The max number of concurrent active trackers
max_active_trackers=10

# Detection Mode
#   one of: 'background_subtraction'
detection_mode='background_subtraction'

calculate_optical_flow=true

# Tracker settings
#   these settings help ensuer that trans are not orphaned and do not remain stationary for a long time
#   generally I have found that stationary tracks are false positives and not good targets
#
#   Enable this by by setting the validation flag to true, its highly encouraged that this option is enabled
min_centre_point_distance_between_bboxes=64
enable_track_validation=true
stationary_track_threshold=5
orphaned_track_threshold=20

# Bounding Boxes setting
#   fix the size of the bounding box
bbox_fixed_size=false
bbox_size=64

# Track Plotting
track_plotting_enabled=true

# Track Predicting
track_prediction_enabled=false

[Mask]

# Mask types supported
#   one of: 'fish_eye', 'overlay', 'overlay_inverse'
#   each option has it's own parameters, see below
#   NOTE: 'fish_eye' does not support cuda and will fallback to no_op

type='fish_eye'
mask_pct=20

#type='overlay'
#type='overlay_inverse'
#overlay_image_path='masks/test_mask.jpg'

[Camera]

camera_mode='rtsp'
camera_iteration_interval=10
# N.B. place camera_uri in secrets.toml

[MOTSTF]
write_original=true
write_annotated=true
write_images=true
write_training_images=true