
# [Multiple,Single] Object Tracking
#   one of: ['none', 'mot_stf','sot_stf']
output_format='mot_stf'

# The following dumpers give the ability to dump out video frames, mainly used for debugging purposes
#   ['none', dump_original', 'dump_grey', 'dump_optical_flow', 'dump_annotated', 'dump_masked_background', 'all']
frame_dumpers='none'

input_dir='input'
output_dir='output'

# Options
#  video = video playback
#  camera = camera stream
controller='video'

[Visualizer]

# Options
#  noop = No visualisation at all, just a console entry
#  simple = Displays single image with annotations, annotations are also in console output
#  two_by_two = Displays 2x2 images incl image with annotations, background subtraction and keypoints, annotations
#    are also in console output
format='two_by_two'
max_display_dim=1080


[VideoTracker]

tracker_type='CSRT'

enable_cuda=false
enable_stopwatch=false

# Detects small, medium and large objects
sensitivity=1
resize_frame=false
resize_dimension=1440
noise_reduction=false
blur_radius=3

# The max number of concurrent active trackers
max_active_trackers=10

# Detection Mode
#   one of: 'background_subtraction'
detection_mode='background_subtraction'

calculate_optical_flow=true

# Tracker settings
#   these settings help ensuer that trans are not orphaned and do not remain stationary for a long time
#   generally I have found that stationary tracks are false positives and not good targets
#
#   Enable this by by setting the validation flag to true, its highly encouraged that this option is enabled
enable_track_validation=true
stationary_track_threshold=5
orphaned_track_threshold=20

[Mask]

type='fish_eye'
mask_pct=20

[Camera]

camera_mode='rtsp'
# N.B. place camera_uri in secrets.toml
