
# [Multiple,Single] Object Tracking
#   one of: ['mot_stf','sot_stf']
output_format = 'mot_stf'

input_dir = 'input'
output_dir = 'output'

controller = 'video'

[Visualizer]

format = 'two_by_two'
max_display_dim = 1080


[VideoTracker]

mask_pct=20

# Detects small, medium and large objects
sensitivity=1

normalize=false

blur=false

# Detection Mode
#   one of: 'background_subtraction'
detection_mode='background_subtraction'

calculate_optical_flow=true

[Camera]

camera_mode = 'rtsp'
# N.B. place camera_uri in secrets.toml
