
# [Multiple,Single] Object Tracking
#   one of: ['none', 'mot_stf','sot_stf']
# The following writers give the ability to dump out video frames, mainly used for debugging purposes
#   ['dump_original', 'dump_grey', 'dump_optical_flow', 'dump_annotated', 'dump_masked_background']
output_format = 'mot_stf'

input_dir = 'input'
output_dir = 'output'

# Options
#  video = video playback
#  video_cuda = video playback with cuda support
#  camera = camera stream
#  camera_cuda = camera stream with cuda support
controller = 'video'

[Visualizer]

# Options
#  noop = No visualisation at all, just a console entry
#  simple = Displays single image with annotations, annotations are also in console output
#  two_by_two = Displays 2x2 images incl image with annotations, background subtraction and keypoints, annotations
#    are also in console output
format = 'two_by_two'
max_display_dim = 1080


[VideoTracker]

mask_pct=20
# Detects small, medium and large objects
sensitivity=1
resize_frame=false
noise_reduction=false

# Options
# BOOSTING, MIL, KCF, TLD, MEDIANFLOW, GOTURN, MOSSE, CSRT, DASIAMRPN
tracker_type='CSRT'

# Options
# KNN, MOG2, MOG2_CUDA
# Note: MOG2_CUDA is currently the only supported option for cuda and if not set it will default to that
background_subtractor_type='KNN'

# The max number of concurrent active trackers
max_active_trackers=10

# Detection Mode
#   one of: 'background_subtraction'
detection_mode='background_subtraction'

calculate_optical_flow=true

[Camera]

camera_mode = 'rtsp'
# N.B. place camera_uri in secrets.toml
