
# Format options: ['dev','stf']
format = 'mot_stf'

input_dir = 'videos/samples'

output_dir = 'videos/out'


[VideoTracker]

mask_pct=80
sensitivity=1
normalize=false

[Camera]

camera_mode = 'rtsp'
